meetings:
  20141203_bopec:
    agenda_id: 2308
    agenda_packet_id: 2309
    minutes_id: 2416
    youtube_id: "Hp3NtLl05bk"
    youtube_length: "19:43"
  20141217_commission:
    agenda_id: 2325
    agenda_packet_id: 2324
    minutes_id: 2398
    minutes_draft: False
    youtube_id: "zzBeTGAnJy8"
    youtube_length: "53:23"
  20150107_bopec:
    status: canceled
  20150121_commission:
    agenda_id: 2357
    agenda_packet_id: 2359
    minutes_id: 2455
    youtube_id: "LfwRZn0j20Y"
    youtube_length: "1:00:08"
  20150204_bopec:
    agenda_id: 2406
    agenda_packet_id: 2405
    youtube_id: "6YcL7Biv5c8"
    youtube_length: "53:27"
  20150218_commission:
    agenda_id: 2435
    agenda_packet_id: 2419
  20150304_bopec:
    status: TBD
  20150318_commission:
    status: TBD
  20150401_bopec:
    status: TBD
