meetings:
  2014_12_17_commission:
    status: TBD
    agenda_id: 2325
    agenda_packet_id: 2324
    minutes_id: 2353
    youtube_id: "zzBeTGAnJy8"
  2015_01_07_bopec:
    status: canceled
  2015_01_21_commission:
    status: TBD
