meetings:
  20141217_commission:
    status: TBD
    agenda_id: 2325
    agenda_packet_id: 2324
    minutes_id: 2398
    minutes_draft: False
    youtube_id: "zzBeTGAnJy8"
    youtube_length: "53:23"
  20150107_bopec:
    status: canceled
  20150121_commission:
    agenda_id: 2357
    agenda_packet_id: 2359
    youtube_id: "LfwRZn0j20Y"
    youtube_length: "1:00:08"
  20150204_bopec:
    agenda_id: 2406
    agenda_packet_id: 2405
  20150218_commission:
    status: TBD
  20150304_bopec:
    status: TBD
  20150318_commission:
    status: TBD
