meetings:
  2014_12_17_commission:
    status: TBD
    agenda_id: 2325
    agenda_packet_id: 2324
    minutes_id: 2353
    minutes_draft: True
    youtube_duration: "53:23"
    youtube_id: "zzBeTGAnJy8"
  2015_01_07_bopec:
    status: canceled
  20150121_commission:
    agenda_id: 2357
    agenda_packet_id: 2359
    youtube_id: "LfwRZn0j20Y"
    youtube_length: "1:00:08"
  2015_02_04_bopec:
    status: TBD
  2015_02_18_commission:
    status: TBD
